name: Lint, Test, Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
#    container:
#      image: genrl/ubuntu-build:latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6','3.7','3.8' ]
    
    name: Lint, Build and Code Coverage for Python ${{ matrix.python-version }}
       
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort codecov pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint check
        run: |
          flake8 .
          black --check .
          isort -c .

      - name: Tests
        run: pytest --cov-report xml --cov='./genrl/' --cov-config=.coveragerc

      - name: Code Coverage CodeCov.io
        shell: bash
        run: codecov --token=16dca61f-670e-4a9a-bda6-e016cb5579db
